[green_agent]
agentbeats_id = "019bc407-69cf-7bc3-85ce-b1a05830277c"
env = { API_KEY = "${GITHUB_SECRET_NAME}", HF_TOKEN = "${HF_TOKEN}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "test_taker"
env = {}
s

[config]
questions_limit = "none"